### ISSUE TITLE
(+ Workaround) “Fortnite” cannot be opened because the developer did not intend for it to run on this Mac

### ISSUE THREAD

**Issue by amemoia** [isacucho/FnMacAssistant#1]
Installing the fullscreen-patched version can cause an error message to appear. As found under [this Reddit thread](https://www.reddit.com/r/macgaming/comments/1f66ojr/a_guide_on_how_to_install_fortnite_on_mac/), it's likely related to editing the Info.plist file. FnMacAssistant only shows one file with the fullscreen patch in its download picker.

Workaround:
If you changed the Info.plist manually, restore the original version.
Alternatively, grab an .ipa from the Celestial Discord and sideload it as normal.

Suggestion:
Only offer non-patched downloads while the underlying issue isn't fixed

**Comment by isacucho** [comment]
I was planning to re-upload the other IPAs to the app as well, I plan to add them in the next hour to the dropdown menu. I don't know why sometimes after sideloading the app it may give that error message, but in the devices I tested it with after the second or third try it worked. 

Also make sure you press the patch button before trying to open it. If you had another version of Fortnite on your Mac before, the new one will be saved as Fortnite-1.app. The patch button should remove the old app (while keeping the files) and renaming the new one before patching the embedded.mobileprovision. You can test if the new install works by opening Fortnite-1.app, and if it opens and then crashes, it means it will work after patch. 

The only difference the fullscreen app has is the added key in the info.plist. I didn't paste the whole file they had in the Reddit post, since that made the app not open, but I only added the key that made it work. It works on my device and it works on my friend's so I'm not sure why it may not work for you. 

Also, the problem might be that the new app is saved as Fortnite [date] instead of Fortnite-1. My friend had that problem and to solve it, we had to delete the old Fortnite.app and rename the new one to Fortnite.app, then press patch on the app. I haven't found a way to implement an automatic fix for this, but as soon as I solve it I will post an update. 

Nevertheless, I'll add the other two IPAs from the celestial discord to the app's dropdown menu. There's no need to download app update, the app will fetch the newest releases automatically. 

I hope this helps!

**Comment by Ghostkwebb** [comment]
> I was planning to re-upload the other IPAs to the app as well, I plan to add them in the next hour to the dropdown menu. I don't know why sometimes after sideloading the app it may give that error message, but in the devices I tested it with after the second or third try it worked.
> 
> Also make sure you press the patch button before trying to open it. If you had another version of Fortnite on your Mac before, the new one will be saved as Fortnite-1.app. The patch button should remove the old app (while keeping the files) and renaming the new one before patching the embedded.mobileprovision. You can test if the new install works by opening Fortnite-1.app, and if it opens and then crashes, it means it will work after patch.
> 
> The only difference the fullscreen app has is the added key in the info.plist. I didn't paste the whole file they had in the Reddit post, since that made the app not open, but I only added the key that made it work. It works on my device and it works on my friend's so I'm not sure why it may not work for you.
> 
> Also, the problem might be that the new app is saved as Fortnite [date] instead of Fortnite-1. My friend had that problem and to solve it, we had to delete the old Fortnite.app and rename the new one to Fortnite.app, then press patch on the app. I haven't found a way to implement an automatic fix for this, but as soon as I solve it I will post an update.
> 
> Nevertheless, I'll add the other two IPAs from the celestial discord to the app's dropdown menu. There's no need to download app update, the app will fetch the newest releases automatically.
> 
> I hope this helps!

Yea nothing is working for me :(

**Comment by isacucho** [comment]
> Yea nothing is working for me :(
> 
Some people have told me that to solve this issue you may need to delete the fortnite app (go to applications folder and drag Fortnite.app to the trash), installing the IPA with sideloadly again, but this time before pressing the patch button try to open the app. It should launch for a few moments, then crash. After that, press the patch button and try to open Fortnite again. 

If it doesn't work, make sure your Mac is on the latest macOS version, and update if it isn't. 

Let me know if it works! For easier contact and troubleshooting, you can shoot me a dm on discord: @isacucho and I'll do my best to help!

**Comment by Ghostkwebb** [comment]
> > Yea nothing is working for me :(
> 
> Some people have told me that to solve this issue you may need to delete the fortnite app (go to applications folder and drag Fortnite.app to the trash), installing the IPA with sideloadly again, but this time before pressing the patch button try to open the app. It should launch for a few moments, then crash. After that, press the patch button and try to open Fortnite again.
> 
> If it doesn't work, make sure your Mac is on the latest macOS version, and update if it isn't.
> 
> Let me know if it works! For easier contact and troubleshooting, you can shoot me a dm on discord: @isacucho and I'll do my best to help!

Thanks for the help for now I just downloaded the ipa from celestial and it seems to be working I'll try what u said as well ( also I'm on the latest macOS 15 version)
