### ISSUE TITLE
More Natural Mouse Movement

### ISSUE THREAD

**Issue by KohlerVG** [isacucho/FnMacAssistant#2]
Your app works brilliantly! The only problem is when using a mouse (I have a razer basilisk v3 pro) it sometimes go to far when you want to do a quick 180 shot. Is there something that can map the controls better? I know apples has their little but not very customizable controls emulations settings. I would like to help with this to make it 100% playable. I'm curious to see if anyone has any ideas on how to customize the controls further.

**Comment by isacucho** [comment]
Thanks! Yeah, the keyboard and mouse thing has been an issue since the beginning. This implementation of keyboard and mouse on Fortnite mobile is not made by me, it was actually in the native app. I have been looking for a way to get it to work better, but no luck so far. I’ve been looking for a way to inject playcover’s playtools to test their keymapping, but so far the app crashes when injecting it. I truly want this to work some day so if you find something or help with this in some way, I would really appreciate your help!

**Comment by KohlerVG** [comment]
Absolutely! I'd love to see full mouse and keyboard support become a reality for sideloaded IPA files on Apple Silicon Macs, as the current options lack customization.

I’m considering using Karabiner-Elements with either AppleScript or Python to translate mouse and keyboard inputs into Xbox controller inputs. I’ll give it a try and see how it goes! It would also be great to find a way to integrate PlayCover’s keymapper, as it's further along in development and could potentially offer a smoother solution.

**Comment by isacucho** [comment]
Great, that would be really helpful! We could keep in contact through discord if you want, that way we would have a more direct chat and we can work on this together! My discord user is _isacucho_

**Comment by KohlerVG** [comment]
Sure thing! I'll connect with you in discord.
