### ISSUE TITLE
How to update Fortnite?

### ISSUE THREAD

**Issue by DestructoDisk** [isacucho/FnMacAssistant#6]
I just  installed the game today and everything seems to be working as far as getting the game to boot up on my Mac. However after the game is booted downloads the resources it needs from within the game, and when that download is finished it says "an update is available and required". When I click the yellow update button, it takes em to the Fortnite desktop website where there is no option to proceed with an update for the mobile version I am running.

**Comment by isacucho** [comment]
Hi! Since the newest update was just released today, we had to wait for it to be extracted and uploaded before I could apply the fullscreen patch and upload the IPA to the app. 

The newest IPA is now available. You should now be able to download it using the app and install it with sideloadly. Then patch app. If you get an error, reinstall and try to open Fortnite-1.app before patching.

when you open the game, it should download around 2gb of update files and then it should prompt you to log in.
